# Generated by Django 3.2.8 on 2021-10-19 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.TextField(max_length=200, verbose_name='Profile Label')),
                ('label', models.TextField(max_length=200, verbose_name='Profile Label')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Profile Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Profile Updated')),
                ('steps', models.IntegerField(blank=True, default=0, null=True, verbose_name='steps')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Step Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Step Updated')),
                ('start', models.TextField(verbose_name='Step Start')),
                ('end', models.TextField(verbose_name='Step End')),
                ('b', models.IntegerField(blank=True, default=0, null=True, verbose_name='Blue PCT')),
                ('r', models.IntegerField(blank=True, default=0, null=True, verbose_name='Deep Red PCT')),
                ('g', models.IntegerField(blank=True, default=0, null=True, verbose_name='Green PCT')),
                ('f', models.IntegerField(blank=True, default=0, null=True, verbose_name='Far Red PCT')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NX3.profile', verbose_name='Profile')),
            ],
        ),
    ]
