# Generated by Django 3.2.8 on 2021-10-20 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NX3', '0002_userprofile_userprofilestep'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Step Updated')),
                ('signal', models.IntegerField(blank=True, default=0, null=True, verbose_name='Signal Strenght')),
                ('ap', models.TextField(blank=True, default='WiFi Network', null=True, verbose_name='Wifi ESSID')),
                ('sta', models.TextField(blank=True, default='STA', null=True, verbose_name='STA/AP Mode')),
                ('gw', models.TextField(blank=True, default=0, null=True, verbose_name='Gateway Address')),
                ('v48', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='48V Bus Voltage')),
                ('t1', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='PCB 1 Temp')),
                ('t2', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='PCB 2 Temp')),
                ('t3', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='PCB 3 Temp')),
                ('fan', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Fan Power')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='NX3.profile', verbose_name='Profile')),
                ('profileStep', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='NX3.profilestep', verbose_name='Profile')),
            ],
        ),
    ]
