# Generated by Django 3.2.8 on 2021-10-20 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NX3', '0003_systemstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemstate',
            name='state_id',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='State ID'),
        ),
        migrations.AlterField(
            model_name='systemstate',
            name='profileStep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='NX3.profilestep', verbose_name='Profile Step'),
        ),
    ]
