# Generated by Django 3.2.8 on 2021-10-20 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NX3', '0004_auto_20211020_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemstate',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='NX3.profile', verbose_name='Profile'),
        ),
        migrations.AlterField(
            model_name='systemstate',
            name='profileStep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='NX3.profilestep', verbose_name='Profile Step'),
        ),
    ]
